#!/usr/bin/env bash
# Summary: Detect the file that sets the current cfenv version
set -e
[ -n "$CFENV_DEBUG" ] && set -x

find_local_version_file() {
  local root="$1"
  while [ -n "$root" ]; do
    if [ -e "${root}/.railo-version" ]; then
      echo "${root}/.railo-version"
      exit
    elif [ -e "${root}/.cfenv-version" ]; then
      echo "${root}/.cfenv-version"
      exit
    fi
    root="${root%/*}"
  done
}

find_local_version_file "$CFENV_DIR"
[ "$CFENV_DIR" = "$PWD" ] || find_local_version_file "$PWD"

global_version_file="${CFENV_ROOT}/version"

if [ -e "$global_version_file" ]; then
  echo "$global_version_file"
elif [ -e "${CFENV_ROOT}/global" ]; then
  echo "${CFENV_ROOT}/global"
elif [ -e "${CFENV_ROOT}/default" ]; then
  echo "${CFENV_ROOT}/default"
else
  echo "$global_version_file"
fi
