#!/usr/bin/env bash
# Summary: Explain how the current CFML version is set
set -e
[ -n "$CFENV_DEBUG" ] && set -x

if [ -n "$CFENV_VERSION" ]; then
  echo "CFENV_VERSION environment variable"
else
  cfenv-version-file
fi
