#!/usr/bin/env bash
# Summary: Show the current CFML version and its origin
#
# Shows the currently selected CFML version and how it was
# selected. To obtain only the version string, use `cfenv
# version-name'.

set -e
[ -n "$CFENV_DEBUG" ] && set -x

echo "$(cfenv-version-name) (set by $(cfenv-version-origin))"
