#!/usr/bin/env bash
set -e
[ -n "$CFENV_DEBUG" ] && set -x

# Provide cfenv completions
if [ "$1" = "--complete" ]; then
  exec cfenv-rehash --complete
fi

shell="$(basename "${CFENV_SHELL:-$SHELL}")"

# When cfenv shell integration is enabled, delegate to cfenv-rehash,
# then tell the shell to empty its command lookup cache.
cfenv-rehash

case "$shell" in
fish )
  # no rehash support
  ;;
* )
  echo "hash -r 2>/dev/null || true"
  ;;
esac
