#!/usr/bin/env bash
#
# Summary: Set or show the shell-specific CFML version
#
# Usage: cfenv shell <version>
#        cfenv shell --unset
#
# Sets a shell-specific CFML version by setting the `CFENV_VERSION'
# environment variable in your shell. This version overrides local
# application-specific versions and the global version.
#
# <version> should be a string matching a CFML version known to cfenv.
# The special version string `system' will use your default system CFML.
# Run `cfenv versions' for a list of available CFML versions.

set -e
[ -n "$CFENV_DEBUG" ] && set -x

# Provide cfenv completions
if [ "$1" = "--complete" ]; then
  echo --unset
  echo system
  exec cfenv-versions --bare
fi

version="$1"
shell="$(basename "${CFENV_SHELL:-$SHELL}")"

if [ -z "$version" ]; then
  if [ -z "$CFENV_VERSION" ]; then
    echo "cfenv: no shell-specific version configured" >&2
    exit 1
  else
    echo "echo \"\$CFENV_VERSION\""
    exit
  fi
fi

if [ "$version" = "--unset" ]; then
  case "$shell" in
  fish )
    echo "set -e CFENV_VERSION"
    ;;
  * )
    echo "unset CFENV_VERSION"
    ;;
  esac
  exit
fi

# Make sure the specified version is installed.
if cfenv-prefix "$version" >/dev/null; then
  case "$shell" in
  fish )
    echo "setenv CFENV_VERSION \"${version}\""
    ;;
  * )
    echo "export CFENV_VERSION=\"${version}\""
    ;;
  esac
else
  echo "false"
  exit 1
fi
